### ISSUE TITLE
使用FiftyOne下载Open Images V6的速度很慢 

### ISSUE THREAD

**Issue by Zhang-Yexun** [bcmi/Foreground-Object-Search-Dataset-FOSD#1]
![image](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/140472860/179969bd-d61c-480b-b806-88eb0c40178e)
请问作者，有没有更快的下载方式，谢谢！

**Comment by charlessjc** [comment]
@Zhang-Yexun 你好，我在使用fiftyone下载时没有遇到过此问题，通常来说配置合适的代理可能是有效的。同样，你也可以尝试手动进行下载[Open Images v6](https://storage.googleapis.com/openimages/web/download_v6.html)，不过手动下载完成后可能需要调整数据集文件结构。
