### ISSUE TITLE
按照requirement.txt中的numpy版本不能使用import fiftyone

### ISSUE THREAD

**Issue by Zhang-Yexun** [bcmi/Foreground-Object-Search-Dataset-FOSD#2]
![image](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/140472860/617c957a-7541-4a53-bfd7-084c7f03aa4b)

![image](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/140472860/a86eae09-b807-4010-b59a-569d1cac89bd)
请问作者遇到过这种情况吗，按照requirement.txt安装的numpy的版本，但是使用import fiftyone就遇到了这个问题（这个问题刚开始是没有的）。
然后问了GPT也没有很好的解决，下面的链接点进去出来的这个是我当时询问chatGPT的界面，解决问题，https://chat.openai.com/share/0b7c3beb-a26c-465d-9f6f-a1957a9a6853

**Comment by charlessjc** [comment]
@Zhang-Yexun 你好，我曾在别的项目中遇到过相关问题，你可以尝试将冲突的包的版本号删掉并再次安装。
