### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by Zhang-Yexun** [bcmi/Foreground-Object-Search-Dataset-FOSD#3]
打扰了！这个问题感觉有点弱智。
当时我通过fiftyone下载Open-Images-v6 dataset数据集，
使用的代码是：
import fiftyone as fo
dataset = fo.zoo.load_zoo_dataset("open-images-v6")
然后我下载的Open-Images-v6的数据结构与给定的数据结构不一样
![image](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/140472860/ed1ada76-fc6b-4d9d-a6de-51c4d2bb51b5)
如上图所示在Open-Images-v6的下级目录我少了一个metadata，然鹅这个metadata在train文件夹下
![image](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/140472860/a92e2498-34ae-4b83-90fa-102291374083)
我的Open-Images-v6 dataset数据集的数据结构是这样的：
Open-Images-v6
├── train
│   ├── data
│   │   ├── xxx.jpg
│   │   ├── xxx.jpg
│   │   ...
│   │
│   └── labels
│       └── masks
│       │   ├── 0
│       │       ├── xxx.png
│       │       ├── xxx.png
│       │       ...
│       │   ├── 1
│       │   ...
│       │
│       ├── segmentations.csv
│       ...
     └── metadata
          
         ...

所以说这个metadata文件夹要不要移动

**Comment by charlessjc** [comment]
@Zhang-Yexun 你好，我们的数据集的构建仅使用了Open Images v6中的训练集，所以你需要将metadata移动至上层路径中。

**Comment by luojunqi011027** [comment]
请问你运行成功了吗？方便留一个联系方式探讨一下吗？
