### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luojunqi011027** [bcmi/Foreground-Object-Search-Dataset-FOSD#4]
![微信图片_20231104151406](https://github.com/bcmi/Foreground-Object-Search-Dataset-FOSD/assets/143194084/1b63d3bd-d92a-485b-b365-34ecbbf3b562)
请问上面的两个错误怎么解决呢？
还有一个错误就是在路径下找不到segmentations.csv，这个文件，但是我已经放进了

**Comment by charlessjc** [comment]
@luojunqi011027 你好，这两个错误均是argparse在命令行中使用错误导致的，其中open_images_dir参数是必须的，且该参数后应更改为你下载的open images数据集路径。你可以先查阅并学习argparse的使用方法。
