### ISSUE TITLE
About comparative models' code?

### ISSUE THREAD

**Issue by YaziLee** [bcmi/Foreground-Object-Search-Dataset-FOSD#5]
How can I obtain the CFO, UFO, GALA, and FFR models for comparative experiments? Could you please share your code?Thanks!

**Comment by charlessjc** [comment]
@YaziLee These are not our published papers, and it is recommended that you ask the authors of these papers for the code or implement them by yourself.

**Comment by YaziLee** [comment]
Thank you very much for your answer! The above model has been used to run the results in your paper. Can we reuse your code? Thank you.
